#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAO_DIEN_CNPM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_Gia_Pha")]
	public partial class Gia_PhaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDANG_NHAP_TK(DANG_NHAP_TK instance);
    partial void UpdateDANG_NHAP_TK(DANG_NHAP_TK instance);
    partial void DeleteDANG_NHAP_TK(DANG_NHAP_TK instance);
    partial void InsertTHONG_TIN_TV(THONG_TIN_TV instance);
    partial void UpdateTHONG_TIN_TV(THONG_TIN_TV instance);
    partial void DeleteTHONG_TIN_TV(THONG_TIN_TV instance);
    #endregion
		
		public Gia_PhaDataContext() : 
				base(global::GIAO_DIEN_CNPM.Properties.Settings.Default.QL_Gia_PhaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Gia_PhaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Gia_PhaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Gia_PhaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Gia_PhaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DANG_NHAP_TK> DANG_NHAP_TKs
		{
			get
			{
				return this.GetTable<DANG_NHAP_TK>();
			}
		}
		
		public System.Data.Linq.Table<THONG_TIN_TV> THONG_TIN_TVs
		{
			get
			{
				return this.GetTable<THONG_TIN_TV>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANG_NHAP_TK")]
	public partial class DANG_NHAP_TK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTK;
		
		private string _MK;
		
		private System.Nullable<byte> _Quyen;
		
		private EntityRef<THONG_TIN_TV> _THONG_TIN_TV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTKChanging(string value);
    partial void OnTenTKChanged();
    partial void OnMKChanging(string value);
    partial void OnMKChanged();
    partial void OnQuyenChanging(System.Nullable<byte> value);
    partial void OnQuyenChanged();
    #endregion
		
		public DANG_NHAP_TK()
		{
			this._THONG_TIN_TV = default(EntityRef<THONG_TIN_TV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTK", DbType="NChar(10)")]
		public string TenTK
		{
			get
			{
				return this._TenTK;
			}
			set
			{
				if ((this._TenTK != value))
				{
					if (this._THONG_TIN_TV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenTKChanging(value);
					this.SendPropertyChanging();
					this._TenTK = value;
					this.SendPropertyChanged("TenTK");
					this.OnTenTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MK", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MK
		{
			get
			{
				return this._MK;
			}
			set
			{
				if ((this._MK != value))
				{
					this.OnMKChanging(value);
					this.SendPropertyChanging();
					this._MK = value;
					this.SendPropertyChanged("MK");
					this.OnMKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="TinyInt")]
		public System.Nullable<byte> Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONG_TIN_TV_DANG_NHAP_TK", Storage="_THONG_TIN_TV", ThisKey="TenTK", OtherKey="MaTV", IsForeignKey=true)]
		public THONG_TIN_TV THONG_TIN_TV
		{
			get
			{
				return this._THONG_TIN_TV.Entity;
			}
			set
			{
				THONG_TIN_TV previousValue = this._THONG_TIN_TV.Entity;
				if (((previousValue != value) 
							|| (this._THONG_TIN_TV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THONG_TIN_TV.Entity = null;
						previousValue.DANG_NHAP_TKs.Remove(this);
					}
					this._THONG_TIN_TV.Entity = value;
					if ((value != null))
					{
						value.DANG_NHAP_TKs.Add(this);
						this._TenTK = value.MaTV;
					}
					else
					{
						this._TenTK = default(string);
					}
					this.SendPropertyChanged("THONG_TIN_TV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONG_TIN_TV")]
	public partial class THONG_TIN_TV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTV;
		
		private string _TenTV;
		
		private System.Nullable<System.DateTime> _NgayGSinh;
		
		private System.Nullable<byte> _GT;
		
		private System.Nullable<System.DateTime> _NgayPSinh;
		
		private string _DC;
		
		private System.Nullable<int> _Doi;
		
		private string _MaTT;
		
		private string _MaNN;
		
		private string _MaQQ;
		
		private EntitySet<DANG_NHAP_TK> _DANG_NHAP_TKs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTVChanging(string value);
    partial void OnMaTVChanged();
    partial void OnTenTVChanging(string value);
    partial void OnTenTVChanged();
    partial void OnNgayGSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGSinhChanged();
    partial void OnGTChanging(System.Nullable<byte> value);
    partial void OnGTChanged();
    partial void OnNgayPSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayPSinhChanged();
    partial void OnDCChanging(string value);
    partial void OnDCChanged();
    partial void OnDoiChanging(System.Nullable<int> value);
    partial void OnDoiChanged();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnMaNNChanging(string value);
    partial void OnMaNNChanged();
    partial void OnMaQQChanging(string value);
    partial void OnMaQQChanged();
    #endregion
		
		public THONG_TIN_TV()
		{
			this._DANG_NHAP_TKs = new EntitySet<DANG_NHAP_TK>(new Action<DANG_NHAP_TK>(this.attach_DANG_NHAP_TKs), new Action<DANG_NHAP_TK>(this.detach_DANG_NHAP_TKs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTV
		{
			get
			{
				return this._MaTV;
			}
			set
			{
				if ((this._MaTV != value))
				{
					this.OnMaTVChanging(value);
					this.SendPropertyChanging();
					this._MaTV = value;
					this.SendPropertyChanged("MaTV");
					this.OnMaTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTV", DbType="NVarChar(35)")]
		public string TenTV
		{
			get
			{
				return this._TenTV;
			}
			set
			{
				if ((this._TenTV != value))
				{
					this.OnTenTVChanging(value);
					this.SendPropertyChanging();
					this._TenTV = value;
					this.SendPropertyChanged("TenTV");
					this.OnTenTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGSinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGSinh
		{
			get
			{
				return this._NgayGSinh;
			}
			set
			{
				if ((this._NgayGSinh != value))
				{
					this.OnNgayGSinhChanging(value);
					this.SendPropertyChanging();
					this._NgayGSinh = value;
					this.SendPropertyChanged("NgayGSinh");
					this.OnNgayGSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GT", DbType="TinyInt")]
		public System.Nullable<byte> GT
		{
			get
			{
				return this._GT;
			}
			set
			{
				if ((this._GT != value))
				{
					this.OnGTChanging(value);
					this.SendPropertyChanging();
					this._GT = value;
					this.SendPropertyChanged("GT");
					this.OnGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPSinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgayPSinh
		{
			get
			{
				return this._NgayPSinh;
			}
			set
			{
				if ((this._NgayPSinh != value))
				{
					this.OnNgayPSinhChanging(value);
					this.SendPropertyChanging();
					this._NgayPSinh = value;
					this.SendPropertyChanged("NgayPSinh");
					this.OnNgayPSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DC", DbType="NVarChar(50)")]
		public string DC
		{
			get
			{
				return this._DC;
			}
			set
			{
				if ((this._DC != value))
				{
					this.OnDCChanging(value);
					this.SendPropertyChanging();
					this._DC = value;
					this.SendPropertyChanged("DC");
					this.OnDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doi", DbType="Int")]
		public System.Nullable<int> Doi
		{
			get
			{
				return this._Doi;
			}
			set
			{
				if ((this._Doi != value))
				{
					this.OnDoiChanging(value);
					this.SendPropertyChanging();
					this._Doi = value;
					this.SendPropertyChanged("Doi");
					this.OnDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="NChar(10)")]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNN", DbType="NChar(10)")]
		public string MaNN
		{
			get
			{
				return this._MaNN;
			}
			set
			{
				if ((this._MaNN != value))
				{
					this.OnMaNNChanging(value);
					this.SendPropertyChanging();
					this._MaNN = value;
					this.SendPropertyChanged("MaNN");
					this.OnMaNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQQ", DbType="NChar(5)")]
		public string MaQQ
		{
			get
			{
				return this._MaQQ;
			}
			set
			{
				if ((this._MaQQ != value))
				{
					this.OnMaQQChanging(value);
					this.SendPropertyChanging();
					this._MaQQ = value;
					this.SendPropertyChanged("MaQQ");
					this.OnMaQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONG_TIN_TV_DANG_NHAP_TK", Storage="_DANG_NHAP_TKs", ThisKey="MaTV", OtherKey="TenTK")]
		public EntitySet<DANG_NHAP_TK> DANG_NHAP_TKs
		{
			get
			{
				return this._DANG_NHAP_TKs;
			}
			set
			{
				this._DANG_NHAP_TKs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANG_NHAP_TKs(DANG_NHAP_TK entity)
		{
			this.SendPropertyChanging();
			entity.THONG_TIN_TV = this;
		}
		
		private void detach_DANG_NHAP_TKs(DANG_NHAP_TK entity)
		{
			this.SendPropertyChanging();
			entity.THONG_TIN_TV = null;
		}
	}
}
#pragma warning restore 1591
